GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.2
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: true
  orientation_mode: 1
  outline_map: true
  orientation_window_size: 1
