local_costmap:
  global_frame: dbot/odom
  robot_base_frame: dbot/base_link
  update_frequency: 1.0 
  publish_frequency: 2.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 6
  height: 6
  resoultion: 0.05
  

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflated_layer, type: "costmap_2d::InflationLayer"}